[Details]
  Icon = "internal/gui/resources/icons/src/tomato.png"
  Name = "impomoro"
  ID = "ru.zhbert.impomoro"
  Version = "0.1"
  Build = 3

[Development]
  HelperText = "This is a simple cross-platform pomodoro timer."

[Release]
  HelperText = "This is a simple cross-platform pomodoro timer."

[LinuxAndBSD]
  GenericName = "impomoro"
  Categories = ["Utilites"]
  Comment = "This is a simple cross-platform pomodoro timer."
  Keywords = ["time", "pomorodo"]
